[metadata]
name = osg-build
version = attr: osgbuild.version.__version__
author = Matyas Selmeci
author_email = matyas@cs.wisc.edu
maintainer = OSG Software Team
maintainer_email = software-discuss@osg-htc.org
description = Tools for RPM development for the OSG Software Stack. This branch does not include scripts requiring Koji.
url = https://github.com/opensciencegrid/osg-build
project_urls =
    Documentation = https://osg-htc.org/technology/software/osg-build-tools/
license = ASL 2.0

[options]
packages =
    osgbuild
    osgbuild.data
include_package_data = True
python_requires = >=3.6
install_requires =
    importlib_resources
scripts =
    fetch-dot-source
    sha1vdt

[options.entry_points]
console_scripts =
    osg-build = osgbuild.main:entrypoint
    osg-import-srpm = osgbuild.importer:main
