#!/bin/bash
# sha1vdt
#
# A quick and dirty script to get the sha1 hash of a file in the upstream directory
# and format it appropriately for inclusion in a .source file.
#
# Usage: sha1vdt <filename>
#
# The filename should be in the upstream directory, i.e. under /p/vdt/public/html/upstream
# or /osgsw/upstream


fail () {
    ret=$1
    shift
    echo "$@" >&2
    exit "$ret"
}


filename=${1?Need filename}
real_filename=$(realpath "$filename") || fail 1 "Couldn't get absolute path of $filename"
[[ -f ${real_filename} ]] || fail 2 "${filename} is not a file"

short_filename=
for prefix in \
    "$(realpath "/osgsw/upstream/")" \
    "$(realpath "/p/vdt/public/html/upstream/")"
do
    if [[ ${real_filename} = ${prefix}* ]]
    then
        short_filename=${real_filename#"${prefix}/"}
        break
    fi
done

if [[ -z ${short_filename} ]]
then
    fail 2 "${filename} is not under one of the upstream directories " \
        "('/osgsw/upstream' or '/p/vdt/public/html/upstream')"
fi

set -o pipefail
sha1sum=$(sha1sum "$filename" | awk '{print $1}') || fail 3 "Error getting sha1sum"
printf "%s sha1sum=%s\n" "$short_filename" "$sha1sum"
